# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Cnidaria's Hall
email: "nutchanon.non@outlook.co.th"
description: >- # this means to ignore newlines until "baseurl:"
  This is Nutchanon Jariyanurut's main page for posting my works.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nutchanonj.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Just The Docs theme.
remote_theme: just-the-docs/just-the-docs

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Aux links for the upper right navigation
aux_links:
  "My Blog":
    - "https://nutchanonj.github.io/myblog/"

nav_external_links:
  - title: My Blog (in Thai)
    url: https://nutchanonj.github.io/myblog/
    hide_icon: false # set to true to hide the external link icon - defaults to false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
